---
- name: Installation et enregistrement des agents Wazuh
  hosts: TEST
  gather_facts: yes

  vars:
    wazuh_manager_ip: 192.168.70.10
    wazuh_manager_port: 1515

  tasks:
    - name: Définir le groupe wazuh basé sur le groupe d’inventaire
      set_fact:
        wazuh_agent_group: >-
          {{
            (group_names
              | difference(['all', 'ungrouped'])
            )
            | first
          }}

    - name: Afficher le nom de l’agent et le groupe wazuh choisi
      debug:
        msg: "Agent name: {{ ansible_hostname }}, Groupes trouvés: {{ group_names }}, Wazuh group: {{ wazuh_agent_group }}"

    - name: Include tasks Debian/Ubuntu
      include_tasks: tasks/debian.yml
      when: ansible_os_family == "Debian"

    - name: Include tasks AlmaLinux / RHEL
      include_tasks: tasks/redhat.yml
      when: ansible_os_family == "RedHat"

    - name: Include tasks Windows
      include_tasks: tasks/windows.yml
      when: ansible_os_family == "Windows"
