- name: Installer et configurer le Wazuh Agent
  hosts: DMZ
  become: yes
  tasks:

    - name: Mettre à jour la liste des paquets
      apt:
        update_cache: yes

    - name: Installer les dépendances (curl + gnupg)
      apt:
        name:
          - curl
          - gnupg
          - apt-transport-https
        state: present

    - name: Télécharger et enregistrer la clé GPG de Wazuh
      shell:
        curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | apt-key add -


    - name: Ajouter le dépôt Wazuh avec signature GPG
      shell:
        echo "deb https://packages.wazuh.com/4.x/apt/ stable main" | tee -a /etc/apt/sources.list.d/wazuh.list

    - name: Mise à jour APT après ajout du dépôt
      apt:
        update_cache: yes

    - name: Installer le Wazuh Agent avec variables d’environnement
      environment:
        WAZUH_MANAGER: "192.168.70.10"
        WAZUH_AGENT_GROUP: "DMZ"
      apt:
        name: wazuh-agent
        state: present

    - name: Recharger systemd
      command: systemctl daemon-reload

    - name: Activer wazuh-agent au démarrage
      systemd:
        name: wazuh-agent
        enabled: yes

    - name: Démarrer wazuh-agent
      systemd:
        name: wazuh-agent
        state: started

    - name: Désactiver temporairement le dépôt Wazuh
      lineinfile:
        path: /etc/apt/sources.list.d/wazuh.list
        regexp: '^deb '
        line: '#deb https://packages.wazuh.com/4.x/apt/ stable main'
        state: present

    - name: Mise à jour finale du cache APT
      apt:
        update_cache: yes
